version: '3.8'

services:
  php:
    container_name: "servidor_php"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    container_name: "meu_servidor_mysql"
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_biblioteca
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
    ports: 
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
