# Configuração personalizada do cluster kind
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings: 
      # Porta do container Docker do kind
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP

      # Porta externa para MySQL
      - containerPort: 30306
        # Porta acessível no MySQL Workbench
        hostport: 30306
        protocol: TCP